include: package:pedantic/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: false

analyzer:
  errors:
    invalid_assignment: warning
    missing_return: error
    dead_code: info
    todo: info