// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeiUhTHiy0MhEYJamcmqeEwUxPenH4fMo',
    appId: '1:1018422454473:web:85faa8c52cbb0736dc8518',
    messagingSenderId: '1018422454473',
    projectId: 'rocketchat-3a145',
    authDomain: 'rocketchat-3a145.firebaseapp.com',
    storageBucket: 'rocketchat-3a145.appspot.com',
    measurementId: 'G-0QYN6R6M6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDplzE4EfZKY6wlJij4kfaDZNqI6J7pxsk',
    appId: '1:1018422454473:android:bfd4b726fc05fea5dc8518',
    messagingSenderId: '1018422454473',
    projectId: 'rocketchat-3a145',
    storageBucket: 'rocketchat-3a145.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaGgPhWaKEpe2XyBVDDlWSLfiVJ4ZjRmc',
    appId: '1:1018422454473:ios:a956107728d6ae66dc8518',
    messagingSenderId: '1018422454473',
    projectId: 'rocketchat-3a145',
    storageBucket: 'rocketchat-3a145.appspot.com',
    androidClientId: '1018422454473-1bn9q2l2t3895v14svg50o1pcsd5geou.apps.googleusercontent.com',
    iosClientId: '1018422454473-bplgk7to0tij58abk6ig782a4t110kag.apps.googleusercontent.com',
    iosBundleId: 'co.smallet.superchat',
  );
}
